import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faCopy,
    faShare,
    faDownload,
    faCheck,
} from '@fortawesome/free-solid-svg-icons';
import {
    faWhatsapp,
    faTwitter,
    faFacebook,
} from '@fortawesome/free-brands-svg-icons';

/**
 * Share & Export Component
 * Provides copy, share, and export functionality for analysis results
 */
const ShareExport = ({ text, result, type = 'analyze' }) => {
    const [copied, setCopied] = useState(false);

    /**
     * Copy results to clipboard
     */
    const handleCopy = async () => {
        try {
            const formattedText = formatResultsForCopy();
            await navigator.clipboard.writeText(formattedText);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error('Failed to copy:', error);
            alert('Failed to copy to clipboard');
        }
    };

    /**
     * Format results for copying
     */
    const formatResultsForCopy = () => {
        let formatted = `📝 Text Analysis Results\n`;
        formatted += `${'='.repeat(50)}\n\n`;
        formatted += `Original Text:\n"${text}"\n\n`;

        if (type === 'analyze' && result) {
            formatted += `Language: ${result.language?.name || 'Unknown'}\n`;
            formatted += `Sentiment: ${result.sentiment?.label || 'Unknown'} (${((result.sentiment?.confidence || 0) * 100).toFixed(1)}%)\n`;

            if (result.toxicity) {
                formatted += `\nToxicity Scores:\n`;
                formatted += `- Toxic: ${((result.toxicity.toxic || 0) * 100).toFixed(1)}%\n`;
                formatted += `- Severe: ${((result.toxicity.severe_toxic || 0) * 100).toFixed(1)}%\n`;
                formatted += `- Obscene: ${((result.toxicity.obscene || 0) * 100).toFixed(1)}%\n`;
            }

            if (result.profanity?.has_profanity) {
                formatted += `\nProfanity: Detected (${result.profanity.word_count} words)\n`;
            }
        } else if (type === 'translate' && result) {
            formatted += `Source Language: ${result.source_language || 'Auto'}\n`;
            formatted += `Target Language: ${result.target_language || 'Unknown'}\n`;
            formatted += `\nTranslation:\n"${result.translated_text || result.translation}"\n`;
        }

        formatted += `\n${'='.repeat(50)}\n`;
        formatted += `Generated by Code-Mix NLP Analyzer\n`;
        formatted += `https://code-mix-for-social-media.netlify.app/\n`;

        return formatted;
    };

    /**
     * Share via Web Share API
     */
    const handleShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: 'NLP Analysis Results',
                    text: formatResultsForCopy(),
                });
            } catch (error) {
                if (error.name !== 'AbortError') {
                    console.error('Error sharing:', error);
                }
            }
        } else {
            alert('Web Share API is not supported in your browser. Use copy instead.');
        }
    };

    /**
     * Share on WhatsApp
     */
    const shareWhatsApp = () => {
        const text = encodeURIComponent(formatResultsForCopy());
        window.open(`https://wa.me/?text=${text}`, '_blank');
    };

    /**
     * Share on Twitter
     */
    const shareTwitter = () => {
        const tweetText = `Just analyzed text using Code-Mix NLP Analyzer! 
Sentiment: ${result?.sentiment?.label || 'Unknown'}
Language: ${result?.language?.name || 'Unknown'}
Check it out: https://code-mix-for-social-media.netlify.app/`;
        window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`, '_blank');
    };

    /**
     * Download as JSON
     */
    const downloadJSON = () => {
        const data = {
            timestamp: new Date().toISOString(),
            text,
            result,
            type,
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `analysis-${Date.now()}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    /**
     * Download as TXT
     */
    const downloadTXT = () => {
        const blob = new Blob([formatResultsForCopy()], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `analysis-${Date.now()}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="bg-white dark:bg-gray-800/90 border border-gray-200 dark:border-gray-700 shadow-lg rounded-xl p-4 sm:p-6">
            <h3 className="text-lg font-semibold mb-4 text-gray-800 dark:text-white flex items-center gap-2">
                <FontAwesomeIcon icon={faShare} className="text-primary-600 dark:text-primary-400" />
                Share & Export
            </h3>

            <div className="space-y-4">
                {/* Primary Actions */}
                <div className="grid grid-cols-2 gap-3">
                    <button
                        onClick={handleCopy}
                        className="flex items-center justify-center gap-2 px-4 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors duration-200 font-medium"
                    >
                        <FontAwesomeIcon icon={copied ? faCheck : faCopy} />
                        {copied ? 'Copied!' : 'Copy'}
                    </button>

                    <button
                        onClick={handleShare}
                        className="flex items-center justify-center gap-2 px-4 py-3 bg-secondary-600 hover:bg-secondary-700 text-white rounded-lg transition-colors duration-200 font-medium"
                    >
                        <FontAwesomeIcon icon={faShare} />
                        Share
                    </button>
                </div>

                {/* Social Media Sharing */}
                <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-2 font-medium">Share on Social Media:</p>
                    <div className="flex gap-2">
                        <button
                            onClick={shareWhatsApp}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors duration-200 text-sm"
                            title="Share on WhatsApp"
                        >
                            <FontAwesomeIcon icon={faWhatsapp} />
                            WhatsApp
                        </button>

                        <button
                            onClick={shareTwitter}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-blue-400 hover:bg-blue-500 text-white rounded-lg transition-colors duration-200 text-sm"
                            title="Share on Twitter"
                        >
                            <FontAwesomeIcon icon={faTwitter} />
                            Twitter
                        </button>
                    </div>
                </div>

                {/* Download Options */}
                <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-2 font-medium">Download Results:</p>
                    <div className="flex gap-2">
                        <button
                            onClick={downloadTXT}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg transition-colors duration-200 text-sm"
                        >
                            <FontAwesomeIcon icon={faDownload} />
                            TXT
                        </button>

                        <button
                            onClick={downloadJSON}
                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg transition-colors duration-200 text-sm"
                        >
                            <FontAwesomeIcon icon={faDownload} />
                            JSON
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ShareExport;
